DROP TABLE IF EXISTS flight_data;
DROP TABLE IF EXISTS route_data;
DROP TABLE IF EXISTS airports_data;

CREATE TABLE IF NOT EXISTS flight_data(
    FL_DATE DATE,
    DOT_CODE INT,
    FL_NUMBER INT,
    CRS_DEP_TIME INT,
    DEP_TIME FLOAT,
    DEP_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF FLOAT,
    WHEELS_ON FLOAT,
    TAXI_IN FLOAT,
    CRS_ARR_TIME INT,
    ARR_TIME FLOAT,
    ARR_DELAY FLOAT,
    CANCELLED FLOAT,
    CANCELLATION_CODE VARCHAR(1),
    DIVERTED FLOAT,
    CRS_ELAPSED_TIME FLOAT,
    ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    ID INT PRIMARY KEY,
    ROUTE_ID INT
);

CREATE TABLE IF NOT EXISTS route_data(
    ORIGIN VARCHAR(4),
    DEST VARCHAR(4),
    ORIGIN_CITY VARCHAR(255),
    DEST_CITY VARCHAR(255),
    ROUTE_ID INT PRIMARY KEY,
    MOST_COMMON_DISTANCE FLOAT
);

CREATE TABLE IF NOT EXISTS airports_data(
    AIRPORT_NAME VARCHAR(4) PRIMARY KEY,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);
