COPY route_data FROM STDIN WITH CSV HEADER DELIMITER ',' NULL AS '';
COPY flight_data FROM STDIN WITH CSV HEADER DELIMITER ','  NULL AS '';
COPY flight_data FROM STDIN WITH CSV HEADER DELIMITER ','  NULL AS '';
COPY flight_data FROM STDIN WITH CSV HEADER DELIMITER ','  NULL AS '';
COPY airports_data FROM STDIN WITH CSV HEADER DELIMITER ','  NULL AS '';