COPY evaluation FROM STDIN WITH CSV HEADER DELIMITER ';' NULL AS '';
COPY model1_prediction FROM STDIN WITH CSV HEADER DELIMITER ','  NULL AS '';
COPY model2_prediction FROM STDIN WITH CSV HEADER DELIMITER ','  NULL AS '';